name: Main
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm -g i pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run dist
      - name: Sign
        uses: tristan-weil/ghaction-checksum-sign-artifact@v1.0.1
        with:
          path: /**/*.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /**/*.zip
